### ISSUE TITLE
issues in README.md profile page

### ISSUE THREAD

**Issue by subhadeepbanerjee2003** [Arindam200/Arindam200#5]
**github commits graph link is not working**

**checkout the code in line no 82**

![Screenshot from 2023-08-15 22-24-32](https://github.com/Arindam200/Arindam200/assets/116381157/1a06acf9-63ce-466c-a6a0-a58a221941a4)

**Comment by Arindam200** [comment]
Thanks for pointing this out! 

Can you fix that?

**Comment by subhadeepbanerjee2003** [comment]
yh i am on it

**Comment by Arindam200** [comment]
Closed as this issue fixed at #6
